### ISSUE TITLE
Doesn't work because of `process.env`

### ISSUE THREAD

**Issue by tv42** [harleylang/deno-react-mwe#2]
FYI, the w in the mwe is no longer true.

```
$ . run.sh
[...]
Check file:///home/tv/z/deno-react-mwe/src/Server.tsx

error: Uncaught ReferenceError: process is not defined
  if (process.env.NODE_ENV !== "production") {
  ^
    at https://cdn.skypack.dev/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:17:3
    at createCommonjsModule (https://cdn.skypack.dev/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:6:10)
    at https://cdn.skypack.dev/-/react-dom@v17.0.1-oZ1BXZ5opQ1DbTh7nu9r/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:16:22
```

See https://github.com/skypackjs/skypack-cdn/issues/127

**Comment by harleylang** [comment]
Thank you for reporting! This is tracked in #1.
